### ISSUE TITLE
Add official "FEGA Node Operations Guidelines" to the website

### ISSUE THREAD

**Issue by jmenglund** [EGA-archive/FEGA-onboarding#37]
### Feature type(s)

Content addition

### Location

Not sure, but perhaps https://ega-archive.github.io/FEGA-onboarding/topics/governance-legal/#2-implement-legal-frameworks

### Description of the change

Add a link to the official "FEGA Node Operations Guidelines" document (pdf?).

### Reason for the change

When we try to work out new routines at our local node, I often find myself looking for official documents to get some guidance. Sometimes I find a document on Google Drive, but it is often hard to know if it really is the latest official version or not. Therefore I think it would be very useful if all the official documents that concern the whole federation could be collected on the onboarding website.

**Comment by malloryfreeberg** [comment]
Great suggestion @jmenglund . I believe you are referring to the document that is currently linked in the onboarding materials [here](https://ega-archive.github.io/FEGA-onboarding/topics/technical-operational/#standards). Maybe we should move it or add a link to it from another location that makes sense? I actually don't mind linking to information from more than one location in the onboarding materials. It is fairly easy to find and update links, and having info linked from multiple sites ensures it can be found in different contexts. Shall we add a link to the document from the Governance and Legal section, as well?

**Comment by malloryfreeberg** [comment]
Hi @jmenglund :) Just pinging again if you have an opinion on another location we can add the FEGA Node Operations Guidelines document so it is easier to find. Thanks!
