### ISSUE TITLE
[BUG]: Broken links

### ISSUE THREAD

**Issue by M-casado** [EGA-archive/FEGA-onboarding#72]
### Bug summary

Noticed broken links within the FEGA onboarding

### To reproduce

Click on the broken links hyperlinks

### Observed behaviour

Either ``40X`` errors, or outdated information is displayed.

### Expected behaviour

The correct content is reached

### Additional context

Related PR: https://github.com/EGA-archive/FEGA-onboarding/pull/71

All hyperlinks of the FEGA onboarding site should be checked. So far, the list of links found to be broken is (see [comment](https://github.com/EGA-archive/FEGA-onboarding/pull/71#discussion_r1384671022))
- Within ``docs/topics/data-metadata-management/index.md``:
  - [x] ``https://ega-archive.org/beacon/#/`` --> ``https://ega-archive.org/about/projects-and-funders/beacon/``
  - [x] ``https://ega-archive.org/ga4gh`` --> ``https://ega-archive.org/about/projects-and-funders/ga4gh/``
  - [ ] ``https://ega-archive.org/beacon-api/`` --> 🤷 
  - [x] ``https://ega-archive.org/data-use-conditions`` --> ``https://ega-archive.org/access/data-access-committee/data-use-ontology/``
  - [ ] ``https://ega.ebi.ac.uk:8052/elixir/tickets/tickets`` --> 🤷 
  - [x] ``https://web3.ega-archive.org/metadata/validation/metadata-schema/`` --> ``https://ega-archive.org/submission/metadata/ega-schema/``
  - [x] ``https://www.youtube.com/watch?v=josXa1CydxA`` --> 🤷 
  - [x] ``https://www.ga4gh.org/docs/ga4ghtoolkit/data-security/Privacy-and-Security-Policy.pdf`` --> (likely) [Data Privacy and Security Policy (v1.0)](https://www.ga4gh.org/document/privacy-and-security-policy/): ``https://www.ga4gh.org/document/privacy-and-security-policy/``
  - [x] ``https://www.ga4gh.org/docs/ga4ghtoolkit/data-security/2016May10_REV_SecInfrastructure.pdf`` --> (perhaps) [DATA SECURITY INFRASTRUCTURE POLICY](https://github.com/ga4gh/data-security/blob/master/DSIP/DSIP_v4.0.md#data-security-infrastructure-policy): ``https://github.com/ga4gh/data-security/blob/master/DSIP/DSIP_v4.0.md`` (not sure if this one is the same as ``2016May10_REV_SecInfrastructure.pdf``, but couldn't find this last)

**Comment by malloryfreeberg** [comment]
The broken `https://ega-archive.org/beacon-api/` link should be updated along with all the Beacon info in this page, as I believe the current status is that Beacon v2 is the supported standard. I suggest moving this fix to a dedicated Issue/PR and ask the Beacon v2 people to confirm all the updates.
