### ISSUE TITLE
[FEATURE]: Logo and acknowledgement for European Commission

### ISSUE THREAD

**Issue by amycurwin** [EGA-archive/FEGA-onboarding#73]
### Feature type(s)

Content addition

### Location

https://ega-archive.github.io/FEGA-onboarding/

### Description of the change

on the main page somewhere we need to acknowledge EC and Elixir-Converge project. Here is the approved text:
“This project has received funding from the European Union’s Horizon 2020 research and innovation programme under grant agreement No 871075”.
or
“This [infrastructure][equipment][insert type of result] is part of a project that has received funding from the European Union’s Horizon 2020 research and innovation programme under grant agreement No 871075”.

What should we call this? Are we acknowledging the onboarding website or FEGA in general? 
Could use: [website], [resource]

EU logo
![eu_flag](https://github.com/EGA-archive/FEGA-onboarding/assets/100564420/5210c70f-c415-4a2c-9747-c6cde48069f8)

### Reason for the change

At the Converge project review by EC it was noticed this was missing.

**Comment by malloryfreeberg** [comment]
Let's just go with "This website", since that is the product which we build with CONVERGE funds.
